# .streamlit/pages.toml

# Page 1: La page d'accueil publique
[[pages]]
path = "pages/Accueil_Contenu.py"
name = "Accueil"
icon = "ğŸ "

# Page 2: La page d'authentification
[[pages]]
path = "pages/Authentification.py"
name = "Authentification"
icon = "ğŸ”’"

# Page 3: Le hub principal (privÃ©)
[[pages]]
path = "pages/Gestion_Dossiers.py"
name = "Gestion des Dossiers"
icon = "ğŸ“"

# Une section pour les outils d'analyse (privÃ©s)
#[[pages]]
# name = "Analyse OpÃ©rateurs"
# icon = "ğŸ“¡"
# is_section = true

# [[pages]]
# path = "pages/Orange_Reunion.py"
# name = "Analyse Orange"
# icon = "ğŸ“Œ"

# [[pages]]
# path = "pages/SRR.py"
# name = "Analyse SRR"
# icon = "ğŸ“Œ"

# [[pages]]
# path = "pages/TELCO.py"
# name = "Analyse TELCO"
# icon = "ğŸ“Œ"

# Une section pour l'admin (privÃ© ou public, selon votre choix)
[[pages]]
name = "Administration"
icon = "âš™ï¸"
is_section = true

[[pages]]
path = "pages/Infos.py"
name = "Informations SystÃ¨me"
icon = "ğŸš¨"
