# .streamlit/secrets.toml

[snowflake]
account = "DXNPXSJ-TGB10277"
user = "STREAMLIT_APP_USER"
password = "MOT_DE_PASSE_TRES_SECURISE"
role = "STREAMLIT_ROLE"
warehouse = "STREAMLIT_WH"
database = "AUTH_DB" # La base de donn√©es pour l'authentification
schema = "PROD"